### ISSUE TITLE
TypeError: JwtStrategy requires a secret or key

### ISSUE THREAD

**Issue by niinpatel** [ip11/Swaggy#16]
When I try to run the server. It gives me the following error on console. 

`/home/nitin/WebstormProjects/SwaggyV2/node_modules/passport-jwt/lib/strategy.js:45
        throw new TypeError('JwtStrategy requires a secret or key');
        ^

TypeError: JwtStrategy requires a secret or key
    at new JwtStrategy (/home/nitin/WebstormProjects/SwaggyV2/node_modules/passport-jwt/lib/strategy.js:45:15)
    at module.exports.passport (/home/nitin/WebstormProjects/SwaggyV2/routes/passport.js:13:5)
    at Object.<anonymous> (/home/nitin/WebstormProjects/SwaggyV2/server.js:26:29)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
`

**Comment by iraviteja** [comment]
https://stackoverflow.com/questions/36533767/nodejs-jwtstrategy-requires-a-function-to-retrieve-jwt-from-requests-error

**Comment by niinpatel** [comment]
Thanks. Fixed the issue.
